services:
  # <media_service> is used to serve your media to the client devices
  <media_service>:
    image: lscr.io/linuxserver/<media_service>
    container_name: <media_service>
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${MEDIA_DIRECTORY}:/data
      - ${INSTALL_DIRECTORY}/config/<media_service>:/config
    # network_mode: host # only required for Plex
    ports: # not needed for Plex
      - 8096:8096 # required for Jellyfin and Emby
    restart: unless-stopped

  # Gluetun is our VPN client
  gluetun:
    image: qmcgaw/gluetun:v3.41.1
    container_name: gluetun
    #profiles: ["disabled"] # Uncomment this line to disable the VPN container
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE}
      - VPN_TYPE=${VPN_TYPE}

      # openvpn specific settings
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_CIPHERS=AES-256-GCM

      # wireguard specific settings
      #- WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      #- WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      #- WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}

      # port forwarding settings
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      #- 'VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c "wget -O- --retry-connrefused --header=\"Authorization: Bearer ${QBITTORRENT_API_KEY}\" --post-data \"json={\\\"listen_port\\\":{{PORT}}}\" http://127.0.0.1:8081/api/v2/app/setPreferences 2>&1"'
      #- 'VPN_PORT_FORWARDING_DOWN_COMMAND=/bin/sh -c "wget -O- --retry-connrefused --header=\"Authorization: Bearer ${QBITTORRENT_API_KEY}\" --post-data \"json={\\\"listen_port\\\":0}\" http://127.0.0.1:8081/api/v2/app/setPreferences 2>&1"'

      - TZ=${TZ}
      #- HTTPPROXY=on
      #- FREE_ONLY=true
    volumes:
      - ${INSTALL_DIRECTORY}/config/gluetun:/gluetun
    ports:
      - 8081:8081/tcp # qbittorrent web UI routed through VPN
      - 8090:8080/tcp # sabnzbd web UI routed through VPN
    restart: unless-stopped

  # qBitorrent is used to download torrents
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.2.3
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8081
    volumes:
      - ${MEDIA_DIRECTORY}:/data
      - ${INSTALL_DIRECTORY}/config/qbittorrent:/config
    network_mode: "service:gluetun"
    #ports: # qbittorrent_ports
    #  - 8081:8081 # qbittorrent
    restart: unless-stopped

  # SABnzbd is used to download from usenet
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    #profiles: ["disabled"] # Uncomment this line to disable the SABnzbd container if you don't use usenet
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_DIRECTORY}:/data
      - ${INSTALL_DIRECTORY}/config/sabnzbd:/config
    network_mode: "service:gluetun"
    #ports: # sabnzbd_ports
    #  - 8090:8080 # sabnzbd
    restart: unless-stopped

  # Radarr is used to query, add downloads to the download queue and index Movies
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_DIRECTORY}:/data
      - ${INSTALL_DIRECTORY}/config/radarr:/config
    ports:
      - 7878:7878
    restart: unless-stopped

  # Sonarr is used to query, add downloads to the download queue and index TV shows
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_DIRECTORY}:/data
      - ${INSTALL_DIRECTORY}/config/sonarr:/config
    ports:
      - 8989:8989
    restart: unless-stopped

  # Prowlarr is our torrent indexer/searcher. Sonarr/Radarr use Prowlarr as a source
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${INSTALL_DIRECTORY}/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  # Bazarr is used to download and categorize subtitles
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_DIRECTORY}:/data
      - ${INSTALL_DIRECTORY}/config/bazarr:/config
    ports:
      - 6767:6767
    restart: unless-stopped

  # Lidarr is used to query, add downloads to the download queue and index Music
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    #profiles: ["disabled"] # Uncomment this line to disable the Lidarr container if you don't use music indexing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_DIRECTORY}:/data
      - ${INSTALL_DIRECTORY}/config/lidarr:/config
    ports:
      - 8686:8686
    restart: unless-stopped

  # Dozzle provides an interface to view logs and conduct basic container management
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_ENABLE_SHELL=true
      - DOZZLE_AUTH_PROVIDER=simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${INSTALL_DIRECTORY}/config/dozzle:/data
    ports:
      - 8777:8080
    restart: unless-stopped

  # Watchtower is going to keep our containers updated
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
